#!/usr/bin/env bash

cmake -DCMAKE_BUILD_TYPE="RELEASE" -B "./build" -S "." -DTYPES="FAST_FIXED(16,8),FIXED(32,16)" -DSIZES="S(36,84)"

@printf "Starting simulation with P = V = VF = FIXED(32,16) and dynamic size S(14,5)"

./build/fluid '--p-type=FIXED(32,16)' '--v-type=FIXED(32,16)' '--vf-type=FIXED(32,16)' './data/1.in'
