#!/usr/bin/env bash

cmake -DCMAKE_BUILD_TYPE="RELEASE" -B "./build" -S "." -DTYPES="FAST_FIXED(16,8),FIXED(32,16)" -DSIZES="S(36,84)"

cmake --build build --target fluid -j 4

./build/fluid '--p-type=FAST_FIXED(16,8)' '--v-type=FAST_FIXED(16,8)' '--vf-type=FAST_FIXED(16,8)' './data/2.in' '--save-to=data/2_save.in' '-j4'
